<a href="https://colab.research.google.com/github/emiliomercuri/EnvHydrology2025/blob/main/aulas/aula05-curva_permanencia/_01_Balan%C3%A7o_H%C3%ADdrico_lendo_da_base_CABra_Parte_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Leitura dos dados da Base CABra

1. Acessar o site da plataforma Catchments Attributes for Brazil (CABra) https://thecabradataset.shinyapps.io/CABra/

2. Baixar os dados **Climate** e **Streamflow**

3. Colocar os arquivos no Google Drive

4. Compartilhar os arquivos (opção "qualquer pessoa com o link") e copiar o link

In [ ]:
import pandas as pd
import numpy
from matplotlib import pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta

In [1]:
# # Atualizar o Google Download
# !pip install --upgrade --no-cache-dir gdown

## Download dos dados na máquina virtual Google

Copiar o código que está no link:
https://drive.google.com/file/d/1TaMLC6-FbfXKltZRvCmGPEGUFwm6NVG8/view?usp=sharing

In [ ]:
# Baixa dados da base CABra
!gdown 1TaMLC6-FbfXKltZRvCmGPEGUFwm6NVG8
!gdown 10Q5W4Lj5Mi3RbEzEBf4vd3CRz5iZiFld

Downloading...
From: https://drive.google.com/uc?id=1TaMLC6-FbfXKltZRvCmGPEGUFwm6NVG8
To: /content/CABra_1_climate_ENS.txt
100% 1.47M/1.47M [00:00<00:00, 27.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=10Q5W4Lj5Mi3RbEzEBf4vd3CRz5iZiFld
To: /content/CABra_1_streamflow.txt
100% 482k/482k [00:00<00:00, 77.4MB/s]

## Leitura dos dados climáticos

In [ ]:
# leitura dos dados com pandas
df_climate = pd.read_csv('CABra_1_climate_ENS.txt',sep='\s+',skiprows=13)
df_climate

,Year,Month,Day,p_ens,tmin_ens,tmax_ens,rh_ens,wnd_ens,srad_ens,et_ens,pet_pm,pet_pt,pet_hg
0,mm,°C,°C,%,m,s¯¹,MJ,m¯²,mm,mm,mm,mm,NaN
1,1980,1,1,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
2,1980,1,2,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
3,1980,1,3,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
4,1980,1,4,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11319,2010,12,27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
11320,2010,12,28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
11321,2010,12,29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
11322,2010,12,30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
11323,2010,12,31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

In [ ]:
# Remove a primeira linha do dataframe
df_climate = df_climate.drop([0])
df_climate

,Year,Month,Day,p_ens,tmin_ens,tmax_ens,rh_ens,wnd_ens,srad_ens,et_ens,pet_pm,pet_pt,pet_hg
1,1980,1,1,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
2,1980,1,2,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
3,1980,1,3,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
4,1980,1,4,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
5,1980,1,5,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11319,2010,12,27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
11320,2010,12,28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
11321,2010,12,29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
11322,2010,12,30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
11323,2010,12,31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

In [ ]:
df_climate.columns

Index(['Year', 'Month', 'Day', 'p_ens', 'tmin_ens', 'tmax_ens', 'rh_ens',
       'wnd_ens', 'srad_ens', 'et_ens', 'pet_pm', 'pet_pt', 'pet_hg'],
      dtype='object')

In [ ]:
ano = df_climate['Year'].values
mes = df_climate['Month'].values
dia = df_climate['Day'].values

In [ ]:
data = []
for i in range(len(df_climate)):
    data.append(ano[i] + '-' + mes[i] + '-' + dia[i])
#data

In [ ]:
lista = []
for i in range(len(df_climate)):
    lista.append(datetime.strptime(data[i], '%Y-%m-%d'))

In [ ]:
df_climate['data'] = lista

In [ ]:
df_climate

,Year,Month,Day,p_ens,tmin_ens,tmax_ens,rh_ens,wnd_ens,srad_ens,et_ens,pet_pm,pet_pt,pet_hg,data
1,1980,1,1,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700,1980-01-01
2,1980,1,2,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825,1980-01-02
3,1980,1,3,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262,1980-01-03
4,1980,1,4,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963,1980-01-04
5,1980,1,5,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256,1980-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11319,2010,12,27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658,2010-12-27
11320,2010,12,28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759,2010-12-28
11321,2010,12,29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866,2010-12-29
11322,2010,12,30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779,2010-12-30
11323,2010,12,31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942,2010-12-31

In [ ]:
df_climate = df_climate.set_index('data')
df_climate

,Year,Month,Day,p_ens,tmin_ens,tmax_ens,rh_ens,wnd_ens,srad_ens,et_ens,pet_pm,pet_pt,pet_hg
data,,,,,,,,,,,,,
1980-01-01,1980,1,1,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
1980-01-02,1980,1,2,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
1980-01-03,1980,1,3,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
1980-01-04,1980,1,4,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
1980-01-05,1980,1,5,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-27,2010,12,27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
2010-12-28,2010,12,28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
2010-12-29,2010,12,29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
2010-12-30,2010,12,30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
2010-12-31,2010,12,31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

In [ ]:
df_climate = df_climate.drop(['Year','Month','Day'], axis=1)
df_climate

,p_ens,tmin_ens,tmax_ens,rh_ens,wnd_ens,srad_ens,et_ens,pet_pm,pet_pt,pet_hg
data,,,,,,,,,,
1980-01-01,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
1980-01-02,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
1980-01-03,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
1980-01-04,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
1980-01-05,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256
...,...,...,...,...,...,...,...,...,...,...
2010-12-27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
2010-12-28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
2010-12-29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
2010-12-30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
2010-12-31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

## Incluindo as unidades nos nomes das colunas

E removendo as colunas antigas

In [ ]:
df_climate['p_ens(mm)'] = df_climate['p_ens']
df_climate['tmin_ens(oC)'] = df_climate['tmin_ens']
df_climate['tmax_ens(oC)'] = df_climate['tmax_ens']
df_climate['rh_ens(%)'] = df_climate['rh_ens']
df_climate['wnd_ens(m/s)'] = df_climate['wnd_ens']
df_climate['srad_ens(MJm-2)'] = df_climate['srad_ens']
df_climate['et_ens(mm)'] = df_climate['et_ens']
df_climate['pet_pm(mm)'] = df_climate['pet_pm']
df_climate['pet_pt(mm)'] = df_climate['pet_pt']
df_climate['pet_hg(mm)'] = df_climate['pet_hg']

df_climate = df_climate.drop(['p_ens','tmin_ens','tmax_ens','rh_ens','wnd_ens',
                              'srad_ens','et_ens','pet_pm','pet_pt','pet_hg'], axis=1)


df_climate

,p_ens(mm),tmin_ens(oC),tmax_ens(oC),rh_ens(%),wnd_ens(m/s),srad_ens(MJm-2),et_ens(mm),pet_pm(mm),pet_pt(mm),pet_hg(mm)
data,,,,,,,,,,
1980-01-01,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
1980-01-02,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
1980-01-03,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
1980-01-04,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
1980-01-05,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256
...,...,...,...,...,...,...,...,...,...,...
2010-12-27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
2010-12-28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
2010-12-29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
2010-12-30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
2010-12-31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

In [ ]:
df_climate_novo = df_climate #[['p_ens(mm)','tmin_ens(oC)','tmax_ens(oC)']]
df_climate_novo

,p_ens(mm),tmin_ens(oC),tmax_ens(oC),rh_ens(%),wnd_ens(m/s),srad_ens(MJm-2),et_ens(mm),pet_pm(mm),pet_pt(mm),pet_hg(mm)
data,,,,,,,,,,
1980-01-01,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700
1980-01-02,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825
1980-01-03,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262
1980-01-04,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963
1980-01-05,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256
...,...,...,...,...,...,...,...,...,...,...
2010-12-27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658
2010-12-28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759
2010-12-29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866
2010-12-30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779
2010-12-31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942

In [ ]:
print(df_climate_novo.dtypes)

p_ens(mm)           object
tmin_ens(oC)        object
tmax_ens(oC)        object
rh_ens(%)           object
wnd_ens(m/s)        object
srad_ens(MJm-2)     object
et_ens(mm)          object
pet_pm(mm)          object
pet_pt(mm)          object
pet_hg(mm)         float64
dtype: object

In [ ]:
# Change multiple columns type
df_climate_novo = df_climate_novo.astype({'p_ens(mm)': float,'tmin_ens(oC)': float, 'tmax_ens(oC)': float,
                                          'rh_ens(%)': float,'wnd_ens(m/s)': float, 'srad_ens(MJm-2)': float,
                                          'et_ens(mm)': float, 'pet_pm(mm)': float, 'pet_pt(mm)':float,
                                          'pet_hg(mm)': float})

In [ ]:
print(df_climate_novo.dtypes)

p_ens(mm)          float64
tmin_ens(oC)       float64
tmax_ens(oC)       float64
rh_ens(%)          float64
wnd_ens(m/s)       float64
srad_ens(MJm-2)    float64
et_ens(mm)         float64
pet_pm(mm)         float64
pet_pt(mm)         float64
pet_hg(mm)         float64
dtype: object

## Leitura dos dados de vazão

In [ ]:
# leitura dos dados com pandas
df_streamflow = pd.read_csv('CABra_1_streamflow.txt',sep='\s+',skiprows=8)
df_streamflow

          Year  Month   Day  Streamflow  Quality
0      (m³s¯¹)    NaN   NaN         NaN      NaN
1         1980   10.0   1.0    1165.800      2.0
2         1980   10.0   2.0    1181.200      2.0
3         1980   10.0   3.0    1194.400      2.0
4         1980   10.0   4.0    1201.000      2.0
...        ...    ...   ...         ...      ...
10953     2010    9.0  26.0     938.606      1.0
10954     2010    9.0  27.0     933.871      1.0
10955     2010    9.0  28.0     931.509      1.0
10956     2010    9.0  29.0     933.871      1.0
10957     2010    9.0  30.0     936.236      1.0

[10958 rows x 5 columns]

In [ ]:
# Remove a primeira linha do dataframe
df_streamflow = df_streamflow.drop([0])
df_streamflow

       Year  Month   Day  Streamflow  Quality
1      1980   10.0   1.0    1165.800      2.0
2      1980   10.0   2.0    1181.200      2.0
3      1980   10.0   3.0    1194.400      2.0
4      1980   10.0   4.0    1201.000      2.0
5      1980   10.0   5.0    1203.200      2.0
...     ...    ...   ...         ...      ...
10953  2010    9.0  26.0     938.606      1.0
10954  2010    9.0  27.0     933.871      1.0
10955  2010    9.0  28.0     931.509      1.0
10956  2010    9.0  29.0     933.871      1.0
10957  2010    9.0  30.0     936.236      1.0

[10957 rows x 5 columns]

In [ ]:
ano = df_streamflow['Year'].values
mes = df_streamflow['Month'].values
dia = df_streamflow['Day'].values

In [ ]:
data = []
for i in range(len(df_streamflow)):
    data.append(ano[i] + '-' + str(int(mes[i])) + '-' + str(int(dia[i])))
#data

In [ ]:
lista = []
for i in range(len(df_streamflow)):
    lista.append(datetime.strptime(data[i], '%Y-%m-%d'))

In [ ]:
df_streamflow['data'] = lista

In [ ]:
df_streamflow = df_streamflow.set_index('data')
df_streamflow

            Year  Month   Day  Streamflow  Quality
data
1980-10-01  1980   10.0   1.0    1165.800      2.0
1980-10-02  1980   10.0   2.0    1181.200      2.0
1980-10-03  1980   10.0   3.0    1194.400      2.0
1980-10-04  1980   10.0   4.0    1201.000      2.0
1980-10-05  1980   10.0   5.0    1203.200      2.0
...          ...    ...   ...         ...      ...
2010-09-26  2010    9.0  26.0     938.606      1.0
2010-09-27  2010    9.0  27.0     933.871      1.0
2010-09-28  2010    9.0  28.0     931.509      1.0
2010-09-29  2010    9.0  29.0     933.871      1.0
2010-09-30  2010    9.0  30.0     936.236      1.0

[10957 rows x 5 columns]

In [ ]:
print(df_streamflow.dtypes)

Year           object
Month         float64
Day           float64
Streamflow    float64
Quality       float64
dtype: object

In [ ]:
df_streamflow['Streamflow(m3/s)'] = df_streamflow['Streamflow']

In [ ]:
df_streamflow_novo = df_streamflow[['Streamflow(m3/s)']]
df_streamflow_novo

            Streamflow(m3/s)
data
1980-10-01          1165.800
1980-10-02          1181.200
1980-10-03          1194.400
1980-10-04          1201.000
1980-10-05          1203.200
...                      ...
2010-09-26           938.606
2010-09-27           933.871
2010-09-28           931.509
2010-09-29           933.871
2010-09-30           936.236

[10957 rows x 1 columns]

# Adicionar a Vazão no outro dataframe

In [ ]:
df_climate_novo['Streamflow(m3/s)'] = df_streamflow_novo['Streamflow(m3/s)']

In [ ]:
df_streamflow_novo.isna().sum()

Streamflow(m3/s)    0
dtype: int64

In [ ]:
df_streamflow_novo

            Streamflow(m3/s)
data
1980-10-01          1165.800
1980-10-02          1181.200
1980-10-03          1194.400
1980-10-04          1201.000
1980-10-05          1203.200
...                      ...
2010-09-26           938.606
2010-09-27           933.871
2010-09-28           931.509
2010-09-29           933.871
2010-09-30           936.236

[10957 rows x 1 columns]

In [ ]:
df_climate_novo

,p_ens(mm),tmin_ens(oC),tmax_ens(oC),rh_ens(%),wnd_ens(m/s),srad_ens(MJm-2),et_ens(mm),pet_pm(mm),pet_pt(mm),pet_hg(mm),Streamflow(m3/s)
data,,,,,,,,,,,
1980-01-01,17.744,20.745,27.849,89.784,1.068,11.593,3.928,3.139,3.652,2.700,NaN
1980-01-02,6.515,20.510,29.676,84.342,0.522,16.139,4.038,4.082,4.934,3.825,NaN
1980-01-03,4.314,21.578,30.517,84.951,0.820,17.680,4.202,4.523,5.406,4.262,NaN
1980-01-04,3.955,22.022,31.363,82.714,1.012,16.178,4.729,4.318,5.017,3.963,NaN
1980-01-05,4.798,21.741,30.880,82.440,1.134,17.508,3.945,4.597,5.379,4.256,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2010-12-27,9.375,22.935,29.573,85.749,1.214,15.057,4.146,3.930,4.688,3.658,NaN
2010-12-28,6.888,22.896,31.206,82.553,1.165,19.261,3.709,4.957,5.922,4.759,NaN
2010-12-29,4.397,23.094,31.305,82.595,1.446,19.609,4.544,5.090,6.033,4.866,NaN
2010-12-30,6.692,22.873,30.114,84.971,1.329,15.503,4.686,4.080,4.818,3.779,NaN
2010-12-31,8.742,22.872,30.631,85.157,1.183,16.059,3.934,4.228,4.990,3.942,NaN

In [ ]:
df_climate_novo.isna().sum()

p_ens(mm)             0
tmin_ens(oC)          0
tmax_ens(oC)          0
rh_ens(%)             0
wnd_ens(m/s)          0
srad_ens(MJm-2)       0
et_ens(mm)            0
pet_pm(mm)            0
pet_pt(mm)            0
pet_hg(mm)            0
Streamflow(m3/s)    366
dtype: int64

In [ ]:
df_clima_vazao = df_climate_novo.dropna()
df_clima_vazao.isna().sum()

p_ens(mm)           0
tmin_ens(oC)        0
tmax_ens(oC)        0
rh_ens(%)           0
wnd_ens(m/s)        0
srad_ens(MJm-2)     0
et_ens(mm)          0
pet_pm(mm)          0
pet_pt(mm)          0
pet_hg(mm)          0
Streamflow(m3/s)    0
dtype: int64

In [ ]:
df_clima_vazao

,p_ens(mm),tmin_ens(oC),tmax_ens(oC),rh_ens(%),wnd_ens(m/s),srad_ens(MJm-2),et_ens(mm),pet_pm(mm),pet_pt(mm),pet_hg(mm),Streamflow(m3/s)
data,,,,,,,,,,,
1980-10-01,4.669,22.521,31.019,85.222,0.694,17.078,3.777,4.381,5.276,4.199,1165.800
1980-10-02,11.884,22.645,31.321,82.020,0.760,15.329,4.022,4.040,4.781,3.780,1181.200
1980-10-03,9.195,22.308,30.400,86.096,0.615,15.450,4.173,3.985,4.791,3.761,1194.400
1980-10-04,9.348,21.887,30.540,85.902,0.691,15.414,3.898,4.003,4.778,3.745,1201.000
1980-10-05,14.407,19.680,26.941,88.454,1.502,11.080,2.477,3.103,3.475,2.521,1203.200
...,...,...,...,...,...,...,...,...,...,...,...
2010-09-26,1.146,23.299,34.851,71.702,1.472,21.459,3.495,5.956,6.675,5.541,938.606
2010-09-27,0.545,22.975,35.614,68.785,1.633,23.953,3.689,6.683,7.431,6.214,933.871
2010-09-28,0.289,24.676,36.276,63.917,1.830,23.573,3.364,6.664,7.406,6.268,931.509
2010-09-29,0.471,24.860,36.267,63.736,1.714,23.042,3.368,6.491,7.252,6.139,933.871
2010-09-30,0.803,24.685,36.694,63.779,1.346,22.727,3.452,6.351,7.163,6.070,936.236

## Exportar o arquivo para CSV

Vamos exportar o Dataframe para um CSV para ler ele mais facilmente na próxima vez.

In [ ]:
df_clima_vazao.to_csv('CABra_1_climate+streamflow_edit.csv')

Fazer o download do arquivo  e salvar no Google Drive. Vamos importá-lo no próximo notebook